---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins
spec:
  replicas: 2
  selector:
    matchLabels:
      app: jenkins
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 40%
      maxUnavailable: 40%
  template:
    metadata:
      labels:
        app: jenkins
        ver: "v1.0"
    spec:
      containers:
      - name: jenkins
        image: jenkins/jenkins:jdk-11
        ports:
        - name: http-port
          containerPort: 8080
        resources:
          limits:
            memory: 2Gi
            cpu: 500m


---
apiVersion: v1
kind: Service
metadata:
  name: jenkins-svc
spec:
  type: NodePort
  selector:
    app: jenkins
  ports:
    - name: jenkins
      port: 8080
      targetPort: 8080
      nodePort: 30009
  



