---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: trail-deploy
spec:
  minReadySeconds: 5
  replicas: 4
  selector:
    matchLabels:
      app: web
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  template:
    metadata:
      labels:
        app: web
        version: "v1.1"
    spec:
      containers:
        - name: web
          image: httpd
          ports:
            - containerPort: 80
          resources:
            limits:
              memory: 256Mi
              cpu: 500m

---
apiVersion: v1
kind: Service
metadata:
  name: web-svc
spec:
  type: NodePort
  selector:
    app: web
  ports:
    - name: web
      port: 80
      targetPort: 80
      nodePort: 30001              