---
apiVersion: v1
kind: Pod
metadata:
  name: mypod
spec:
  containers:
  - name: apache-container
    image: httpd:latest
  - name: alpine-container
    image: alpine:latest
    command: ["sleep", "ld"]
              
