---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-vo
  labels:
    app: web
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      name: deploy-vo
      labels:
        app: web
  strategy:
    type: rollingUpdate
    rollingUpdate:
      maxSurge: 40%
      maxUnavailable: 40%    
    spec:
      containers:
        - name: httpd
          image: httpd:latest
      ports:
        containerPort: 80
          resources:
            limits:
              memory: 256Mi
              cpu: 500m
      readinessProbe:
        httpGet:
          path: /
          port: 80
      volumeMounts:
        mountPath: /tmp
        name: vol-deploy


---
apiVersion: v1
kind: Service
metadata:
  name: web-svc
spec:
  type: clusterIP
  clusterIP: {}
  selector:
    app: web
  ports:
    - name: web
      port: 80
      targetPort: 80

    





        