---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: spring-petclinic-replicaset
  labels:
    app: spc
    env: dev
    version: v3.4.0
spec:
  replicas: 3
  selector:
    matchLabels:
      app: spc
      env: dev
      version: v3.4.0
  template:
    metadata:
      labels:
        app: spc
        env: dev
        version: v3.4.0
    spec:
      containers:
      - name: spring-petclinic
        image: springframeworkguru/spring-petclinic:latest
        ports:
        - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: spring-petclinic-service
  labels:
    app: spc
    env: dev
    version: v3.4.0
spec:
  type: ClusterIP
  selector:
    app: spc
    env: dev
    version: v3.4.0
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
